name: Deploy to AWS S3

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore: ".github/**"

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::790387652718:role/${{ github.event.repository.name }}
        aws-region: us-east-2

    - name: Deploy
      run: |
        account=`aws sts get-caller-identity | jq -r .Account`
        aws s3 sync --sse AES256 . s3://${{ github.event.repository.name }}-${account} --exclude ".git/*" --exclude ".github/*" --delete
